# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3692aef3b7a83f9a5337a9a325694fcc9bcce861400f61b4c68a34c7e47ffa5a40b1039975096cdf1e4b72339913e0d0d507c6726e03d0b618fb74555af8a1f1
  moves_key: FxmkCc2aM964BBT83aHsUe6TQMFU7ixu
  moves_secret: 8mDJ_8m6WL671JO2hjNeOTg8vfQhM9gJwhXJ3_nnuX4tjFrdQ1gH4L3uVM8gDmxP
  facebook_key: 1463681470558821
  facebook_secret: f340c5430484af7cabd9d4d3e391481c

test:
  secret_key_base: 0af9a5447f6245d51642b0928b0c6d13bd53dc639857eaa75b455c232f4fe6f94816f7e8171beb84686165c1ca6b518318d220c672cdda5912b59a1d6f8e14b7
  moves_key: FxmkCc2aM964BBT83aHsUe6TQMFU7ixu
  moves_secret: 8mDJ_8m6WL671JO2hjNeOTg8vfQhM9gJwhXJ3_nnuX4tjFrdQ1gH4L3uVM8gDmxP
  facebook_key: 1463681470558821
  facebook_secret: f340c5430484af7cabd9d4d3e391481c


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
